
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button helloButton;

	private global::Gtk.Entry nameEntry;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.helloButton = new global::Gtk.Button();
		this.helloButton.CanFocus = true;
		this.helloButton.Name = "helloButton";
		this.helloButton.UseUnderline = true;
		this.helloButton.Label = global::Mono.Unix.Catalog.GetString("Hello");
		this.fixed1.Add(this.helloButton);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.helloButton]));
		w1.X = 125;
		w1.Y = 35;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.nameEntry = new global::Gtk.Entry();
		this.nameEntry.CanFocus = true;
		this.nameEntry.Name = "nameEntry";
		this.nameEntry.IsEditable = true;
		this.nameEntry.InvisibleChar = '●';
		this.fixed1.Add(this.nameEntry);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.nameEntry]));
		w2.X = 3;
		w2.Y = 4;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 187;
		this.DefaultHeight = 104;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.helloButton.Pressed += new global::System.EventHandler(this.OnHelloButtonPressed);
	}
}
